---
- hosts:  appservers
  sudo: yes

  tasks:

    - name: Update apt cache
      apt: update_cache=yes

    - name: Upgrade all safe packages
      apt: upgrade=safe

    - name: Install unattended upgrades (Debian/Ubuntu only)
      apt: pkg=unattended-upgrades state=installed
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: 'Make sure unattended-upgrades only installs from $ubuntu_release-security'
      lineinfile: 'dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent'
      when: ansible_distribution == 'Ubuntu'

    - name: Enable passwordless sudo
      lineinfile: 'dest=/etc/sudoers regexp="sudo ALL=NOPASSWD: ALL" line="%sudo ALL=NOPASSWD: ALL" state=present'

